"""empty message

Revision ID: 67aec75fb4a6
Revises: 695847785f47
Create Date: 2021-03-16 09:56:57.208225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67aec75fb4a6'
down_revision = '695847785f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_articles', 'aid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_articles', sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
