"""initial migration add

Revision ID: 695847785f47
Revises: 042d44721547
Create Date: 2021-02-27 14:39:35.870241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695847785f47'
down_revision = '042d44721547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_articles', sa.Column('label', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_articles', 'label')
    # ### end Alembic commands ###
